#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <ctype.h>

static void make_guard(char *dst, size_t dst_size, const char *base) {

	snprintf(dst, dst_size, "ASSET_%s_H", base);
	for (size_t i = 0; dst[i]; ++i) {
		if (!isalnum( (unsigned char) dst[i])) {
			dst[i] = '_';
		} else {
			dst[i] = toupper( (unsigned char) dst[i]);
		}
	}
}

int main(int argc, char **argv) {

	if (argc < 2) {
		fprintf(stderr, "usage: %s file.obj\n", argv[0]);
		return EXIT_FAILURE;
	}

	FILE* in_obj = fopen(argv[1], "r");
	if (!in_obj) {
		perror("fopen input");
		return EXIT_FAILURE;
	}

	// compute base name (strip extension if present)
	const char* dot = strrchr(argv[1], '.');
	size_t base_len = dot ? (size_t)(dot - argv[1]) : strlen(argv[1]);

	char base[512];
	if (base_len >= sizeof(base)) base_len = sizeof(base) - 1;
	memcpy(base, argv[1], base_len);
	base[base_len] = '\0';

	// asset and type names
	char type_name[512];
	char* base_dup = strdup(base);
	base_dup[0] = toupper(base_dup[0]);
	snprintf(type_name, sizeof(type_name), "Asset%s", base_dup);

	char header_file[512];
	snprintf(header_file, sizeof(header_file), "asset_%s.h", base);

	char guard[512];
	make_guard(guard, sizeof(guard), base);

	FILE* out_h = fopen(header_file, "w");
	if (!out_h) {
		perror("fopen output");
		fclose(in_obj);
		return EXIT_FAILURE;
	}

	// first pass: count vertices and faces
	size_t vertex_count = 0;
	size_t vt_count = 0;
	size_t vn_count = 0;
	size_t face_count = 0;

	char *line = NULL;
	size_t len = 0;
	ssize_t read;

	while ( (read = getline(&line, &len, in_obj) ) != -1) {
		if (read == 0) continue;
		if (line[0] == 'v' && line[1] == ' ') {
			vertex_count += 1;
		} else if (line[0] == 'v' && line[1] == 't') {
			vt_count += 1;
		} else if (line[0] == 'v' && line[1] == 'n') {
			vn_count += 1;
		} else if (line[0] == 'f' && line[1] == ' ') {
			face_count += 1;
		}
	}

	// prepare header
	fprintf(out_h, "// This asset was automatically generated by objToC.\n\n");
	fprintf(out_h, "#ifndef %s\n#define %s\n\n", guard, guard);

	fprintf(out_h, "#include \"../mesh_types.h\"\n\n", guard, guard);

	fprintf(out_h, "typedef struct {\n");
	fprintf(out_h, "\tsize_t v_count;\n");
	fprintf(out_h, "\tsize_t vt_count;\n");
	fprintf(out_h, "\tsize_t vn_count;\n");
	fprintf(out_h, "\tsize_t f_count;\n");
	fprintf(out_h, "\tV3f v[%zu];\n", vertex_count);
	fprintf(out_h, "\tV2f vt[%zu];\n", vt_count);
	fprintf(out_h, "\tV3f vn[%zu];\n", vn_count);
	fprintf(out_h, "\tFace f[%zu];\n", face_count);
	fprintf(out_h, "\tV3f min;\n");
	fprintf(out_h, "\tV3f max;\n");
	fprintf(out_h, "} %s;\n\n", type_name);

	fprintf(out_h, "static const %s asset_%s = {\n", type_name, base);
	fprintf(out_h, "\t.v_count = %zu,\n", vertex_count);
	fprintf(out_h, "\t.vt_count = %zu,\n", vt_count);
	fprintf(out_h, "\t.vn_count = %zu,\n", vn_count);
	fprintf(out_h, "\t.f_count = %zu,\n", face_count);

	// second pass: output data
	rewind(in_obj);

	size_t vertex_count_cur = 0;
	size_t face_count_cur = 0;
	size_t vt_count_cur = 0;
	size_t vn_count_cur = 0;
	while ((read = getline(&line, &len, in_obj)) != -1) {

		if (read == 0) continue;

		if (line[0] == 'v' && line[1] == ' ') {

			if (vertex_count_cur == 0) fprintf(out_h, "\t.v = {\n");

			char* buf = strdup(line);

			strtok(buf,  " \n\t");
			char* tok1 = strtok(NULL, " \n\t");
			char* tok2 = strtok(NULL, " \n\t");
			char* tok3 = strtok(NULL, " \n\t");

			if (vertex_count_cur < vertex_count - 1) {
				fprintf(out_h, "\t\t{{ %s, %s, %s }},\n", tok1, tok2, tok3);
				vertex_count_cur += 1;
			} else {
				fprintf(out_h, "\t\t{{ %s, %s, %s }}\n", tok1, tok2, tok3);
				fprintf(out_h, "\t},\n");
			}
			free(buf);

		} else if (line[0] == 'v' && line[1] == 't') {

			if (vt_count_cur == 0) fprintf(out_h, "\t.vt = {\n");

			char* buf = strdup(line);
			strtok(buf, " \n\t");
			char* tok1 = strtok(NULL, " \n\t");
			char* tok2 = strtok(NULL, " \n\t");

			if (vt_count_cur < vt_count - 1) {
				fprintf(out_h, "\t\t{{ %s, %s }},\n", tok1, tok2);
				vt_count_cur += 1;
			} else {
				fprintf(out_h, "\t\t{{ %s, %s }}\n", tok1, tok2);
				fprintf(out_h, "\t},\n");
			}
			free(buf);

		} else if (line[0] == 'v' && line[1] == 'n') {

			if (vn_count_cur == 0) fprintf(out_h, "\t.vn = {\n");

			char* buf = strdup(line);
			strtok(buf, " \n\t");
			char* tok1 = strtok(NULL, " \n\t");
			char* tok2 = strtok(NULL, " \n\t");
			char* tok3 = strtok(NULL, " \n\t");

			if (vn_count_cur < vn_count - 1) {
				fprintf(out_h, "\t\t{{ %s, %s, %s}},\n", tok1, tok2, tok3);
				vn_count_cur += 1;
			} else {
				fprintf(out_h, "\t\t{{ %s, %s, %s}}\n", tok1, tok2, tok3);
				fprintf(out_h, "\t},\n");
			}
			free(buf);

		} else if (line[0] == 'f' && line[1] == ' ') {

			if (face_count_cur == 0) fprintf(out_h, "\t.f = {\n");

			char* buf = strdup(line);

			strtok(buf,  " \n\t");
			char* tok1 = strtok(NULL, " \n\t");
			char* tok2 = strtok(NULL, " \n\t");
			char* tok3 = strtok(NULL, " \n\t");
			int t11, t12, t13, t21, t22, t23, t31, t32, t33;
			char* end;
			if (strchr(tok1, '/')) {
				t11 = (int) strtol(tok1, &end, 10);
				t12 = (int) strtol(end + 1, &end, 10);
				t13 = (int) strtol(end + 1, NULL, 10);
				t21 = (int) strtol(tok2, &end, 10);
				t22 = (int) strtol(end + 1, &end, 10);
				t23 = (int) strtol(end + 1, NULL, 10);
				t31 = (int) strtol(tok3, &end, 10);
				t32 = (int) strtol(end + 1, &end, 10);
				t33 = (int) strtol(end + 1, NULL, 10);

			}

			if (face_count_cur < face_count - 1) {
				fprintf(out_h, "\t\t{ .c1 = { .v = %d, .vt = %d, .vn = %d },\n"
					       "\t\t  .c2 = { .v = %d, .vt = %d, .vn = %d },\n"
					       "\t\t  .c3 = { .v = %d, .vt = %d, .vn = %d }, },\n",
						t11, t12, t13, t21, t22, t23, t31, t32, t33);
				face_count_cur += 1;
			} else {
				fprintf(out_h, "\t\t{ .c1 = { .v = %d, .vt = %d, .vn = %d },\n"
					       "\t\t  .c2 = { .v = %d, .vt = %d, .vn = %d },\n"
					       "\t\t  .c3 = { .v = %d, .vt = %d, .vn = %d }, }\n",
						t11, t12, t13, t21, t22, t23, t31, t32, t33);
				fprintf(out_h, "\t}\n");
			}

			free(buf);
		}
	}

	fprintf(out_h, "};\n\n#endif /* %s */\n", guard);

	free(line);
	fclose(in_obj);
	fclose(out_h);
	return EXIT_SUCCESS;
}

